{{- if .Values.istio.enabled -}}
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ include "userprofile.fullname" . }}-istio-gw
  namespace: {{ .Values.istio.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "{{ .Values.istio.host }}"
  {{- end }}