apiVersion: v1
kind: Service
metadata:
  name: {{ include "${{values.component_id}}.fullname" . }}
  labels:
{{ include "${{values.component_id}}.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.jacocoEnabled | default false }}
    - port: 36320
      targetPort: jacoco-port
      protocol: TCP
      name: jacoco-port
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "${{values.component_id}}.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
