{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "${{values.component_id}}.serviceAccountName" . }}
  labels:
{{ include "${{values.component_id}}.labels" . | indent 4 }}
{{- end -}}
